# path_meshes: ${test_dataset.path_co3d_preprocess}/cuboids
fpaths_meshes: ${test_dataset.fpaths_cuboids}
    #car: ${..path_meshes}/106_12650_23736/cuboid_max_1000.ply

#path_cuboids: ${test_dataset.path_co3d_preprocess}/cuboids
#fpaths_meshes:
#    car: ${..path_cuboids}/car/106_12650_23736.ply

# checkpoint: /scratch/sommerl/exps/06-06_14-36-03/nemo.ckpt
# checkpoint: /misc/lmbraid19/sommerl/exps/06-07_11-18-02/nemo.ckpt
# checkpoint: /scratch/sommerl/exps/06-07_13-32-55/nemo.ckpt
# checkpoint_old: ${platform.path_exps}/NeMo-Classification/classification_saved_model_199.pth


# checkpoint: /misc/lmbraid19/sommerl/exps/06-15_09-11-03_CO3D_NeMo_local/nemo.ckpt
# checkpoint: /misc/lmbraid19/sommerl/exps/06-21_09-56-21_CO3D_NeMo_local/nemo.ckpt
# checkpoint: /misc/lmbraid19/sommerl/exps/06-21_18-05-55_CO3D_NeMo_local/nemo.ckpt
# checkpoint: /misc/lmbraid19/sommerl/exps/06-22_11-10-13_CO3D_NeMo_local/nemo.ckpt

backbone:
    class_name: ResNetExt #  ResNetExt # ResNetExt DINOv2 ResNet

train:
    loss_reg_weight: 0.
    sequences_tform4x4_labeled_count: 3
    sequences_tform4x4_estimated_frames_count: 8
    sequences_tform4x4_estimated_sim_threshold: 0.6
    T: 0.07
    optimizer:
        class_name: torch.optim.Adam
        lr: 1e-4 # 0.0001
        weight_decay: 0.0001

    transform:
        W: 512
        H: 512
        dist: 15.
        center3d_min:
            - -0.5
            - -0.5
            - -0.5
        center3d_max:
            - +0.5
            - +0.5
            - +0.5
    epochs_to_next_ckpt: 6
    epochs_to_next_val: 6
    epochs_to_next_test: 6
    epochs_to_next_forget_est_tforms4x4: 2
    epochs: 100
    batch_accumulate_to_next_step: 2

    visualize:
        live: False
        verts_ncds_in_rgb: False
        net_feats_nearest_verts: False
        seq_added_tform: True

    val_fraction: 0.01

    dataloader:
        num_workers: 4
        batch_size: 12
        pin_memory: True

inference:
    optimizer:
        beta0: 0.4
        beta1: 0.6
        lr: 1e-2 # 5e-2
        epochs: 30

    azim:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 10.
        steps: 10

    elev:
        min: -math.pi / 2
        max: math.pi / 2
        steps: 6

    theta:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 10.
        steps: 10

    #elev:
    #    min: -math.pi / 8
    #    max: math.pi / 4
    #    steps: 6

    #theta:
    #    min: -math.pi / 6
    #    max: math.pi / 6
    #    steps: 3

    dist:
        min: '15.'
        max: '15.'
        steps: 1

    pose_iterative_refine: True
    visualize:
        live: False
        samples: False
        verts_ncds_in_rgb: True
        net_feats_nearest_verts: True
        sim: False

    #inference:
    #    visualize:
    #        live: False
    #        samples: False
    #        verts_ncds_in_rgb: False
    #        net_feats_nearest_verts: False
    #        sim: False
    #
    #    pose_iterative_refine: True
    #
    #    optimizer:
    #        beta0: 0.4
    #        beta1: 0.6
    #        lr: 5e-2 # 5e-2
    #        epochs: 30


test:
    transform:
        W: 512
        H: 512
        dist: 15.

    dataloader:
        num_workers: 4
        batch_size: 4
        pin_memory: True

