path_meshes: ${test_dataset.path_co3d_preprocess}/pcls
fpaths_meshes:
    car: ${..path_meshes}/106_12650_23736/cuboid_max_1000.ply

# checkpoint: /scratch/sommerl/exps/06-06_14-36-03/nemo.ckpt
# checkpoint: /misc/lmbraid19/sommerl/exps/06-07_11-18-02/nemo.ckpt
# checkpoint: /scratch/sommerl/exps/06-07_13-32-55/nemo.ckpt

train:
    epochs: 200
    batch_accumulate_to_next_step: 2

    visualize:
        verts_ncds_in_rgb: False
        net_feats_nearest_verts: False

    val_fraction: 0.01

    dataloader:
        num_workers: 4
        batch_size: 20
        pin_memory: True

    transform:
        width: 512
        height: 512
        distance: 24.

test:
    visualize:
        verts_ncds_in_rgb: True
        net_feats_nearest_verts: True

    dataloader:
        num_workers: 4
        batch_size: 4
        pin_memory: True

    transform:
        width: 512
        height: 512
        distance: 24.

    azim:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 7.
        steps: 6
    elev:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 7.
        steps: 6
    theta:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 7.
        steps: 6
    dist:
        min: '24.'
        max: '24.'
        steps: 1