# checkpoint: ${platform.path_exps}/NeMo-Classification/2022_09_26/classification_saved_model_199.pth
# checkpoint_old: ${platform.path_exps}/NeMo-Classification/classification_saved_model_199.pth

path_cuboids: '${test_dataset.path_pascal3d_preprocess}/cuboids'
fpaths_meshes:
    aeroplane: ${..path_cuboids}/aeroplane.ply
    bicycle: ${..path_cuboids}/bicycle.ply
    boat: ${..path_cuboids}/boat.ply
    bottle: ${..path_cuboids}/bottle.ply
    bus: ${..path_cuboids}/bus.ply
    car: ${..path_cuboids}/car.ply
    chair: ${..path_cuboids}/chair.ply
    diningtable: ${..path_cuboids}/diningtable.ply
    motorbike: ${..path_cuboids}/motorbike.ply
    sofa: ${..path_cuboids}/sofa.ply
    train: ${..path_cuboids}/train.ply
    tvmonitor: ${..path_cuboids}/tvmonitor.ply

train:
    epochs_to_next_ckpt: 5
    epochs_to_next_val: 5
    epochs_to_next_test: -1
    visualize:
        verts_ncds_in_rgb: False
        net_feats_nearest_verts: False

    val_fraction: 0.1

    dataloader:
        num_workers: 4
        batch_size: 20
        pin_memory: True

test:
    visualize:
        verts_ncds_in_rgb: True
        net_feats_nearest_verts: True

    dataloader:
        num_workers: 4
        batch_size: 4
        pin_memory: True

    azim:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 13.
        steps: 12
    elev:
        min: -math.pi / 6.
        max: math.pi / 3.
        steps: 4
    theta:
        min: -math.pi / 6.
        max: math.pi / 6
        steps: 3
    dist:
        min: '5.'
        max: '5.'
        steps: 1


backbone:
    transform:
        width: 512
        height: 512
        distance: 5.