# @package _global_
ablation_name: uniform_sampling
method:
    nemo:
        checkpoint: ${platform.path_exps}/07-12_09-15-12_CO3D_NeMo_lr1e-4_bs24_slurm/nemo.ckpt
        inference:
            sample:
                method: uniform # epnp3d2d uniform

            azim:
                min: '0.'
                max: math.pi * 2 - (math.pi * 2) / 12.
                steps: 12

            elev:
                min: -math.pi / 6
                max: math.pi / 3
                steps: 4

            theta:
                min: -math.pi / 6
                max: math.pi / 6
                steps: 3



train: False
test: True
