# @package _global_
ablation_name: old_checkpoint_uniform_sampling
method:
    nemo:
        checkpoint_old: ${platform.path_exps}/NeMo-Classification/classification_saved_model_199.pth
        fpaths_meshes: ${test_datasets.pascal3d.fpaths_cuboids}
        inference:
            sample:
                method: uniform # epnp3d2d uniform
                uniform:
                    azim:
                        min: '0.'
                        max: math.pi * 2 - (math.pi * 2) / 12.
                        steps: 12

                    elev:
                        min: -math.pi / 6
                        max: math.pi / 3
                        steps: 4

                    theta:
                        min: -math.pi / 6
                        max: math.pi / 6
                        steps: 3

            optimizer:
                beta0: 0.4
                beta1: 0.6
                lr: 2e-2 # 5e-3 5e-2
                epochs: 30 # 30

        test:
            transform:
                W: 800 # 800 512
                H: 640 # 640 512
                dist: 25. # 5. (scale_normalized_to_real) * 5. (default distance used)
                center3d: [0., 0., 0.] #  None

train: False
test: True
