# @package _global_
ablation_name: resnet_dim_128_stride_2

method:
    nemo:
      model:
        backbone:
          class_name: ResNet
          layers_returned: [ 4, 3, 2 ] # always start with depest layer...
        head:
          class_name: ResNet
          conv_blocks:
            out_dims: [ 128 ]
            strides: [ 2 ]


train: True
test: True
