# @package _global_
ablation_name: resnet_dim_2048_128_stride_1_1

method:
    nemo:
      model:
        backbone:
          class_name: ResNet
          layers_returned: [ 4, 3, 2 ] # always start with depest layer...
        head:
          class_name: ResNet
          block_type: 'bottleneck' # 'bottleneck', 'basic'
          conv_blocks:
            out_dims: [ 2048, 128 ]
            strides: [ 1, 1 ]


train: True
test: True
