# @package _global_
defaults:
  - /ablations/nemo_backbone@: _default
  - override /methods/model@method.nemo.model: dinov2_unfrozen

ablation_name: dinov2_unfrozen

train: True
test: True


method:
    nemo:
      model:
        head:
          class_name: ResNet
          block_type: 'bottleneck' # 'bottleneck', 'basic'
          #conv_blocks:
          #  out_dims: [ 128 ] # slightly smaller head to fit on 11 GB