# @package _global_
ablation_name: DINOv2_1e-4
method:
    nemo:
        backbone:
            class_name: DINOv2 # ResNetExt DINOv2
        train:
            optimizer:
                lr: 0.0001 # 0.0001
