# @package _global_
ablation_name: resnet_in_upsampled_dim_2048

method:
    nemo:
      model:
        backbone:
          class_name: ResNet
          weights: 'imagenet1k_v2' # 'imagenet1k_v2' 'imagenet1k_v1' 'none'
          freeze: False
          layers_returned: [ 4, 3, 2 ] # always start with depest layer...
        head:
          class_name: ResNet
          block_type: 'bottleneck' # 'bottleneck', 'basic'
          in_upsampled_dim: 2048
          conv_blocks:
            out_dims: [ 128 ]
            strides: [ 1 ]


train: True
test: True
