# @package _global_
ablation_name: resnet50_unfrozen

method:
    nemo:
      train:
        val: True
      model:
        backbone:
          class_name: ResNet
          freeze: False

train: True
test: True
