# @package _global_
defaults:
    - override /datasets@test_datasets.co3d: co3d_50s_test # co3d_10s_test, co3d_test

ablation_name: debug

test_datasets:
    co3d:
        frames_count_max_per_sequence: 8

method:
    nemo:
        checkpoint: ${platform.path_exps}/08-08_17-27-08_CO3D_NeMo_uniform_train_co3d_3s_slurm/nemo.ckpt

        inference:
            visualize:
                live: False

        test:
            dataloader:
                num_workers: 4
                batch_size: 4
                pin_memory: True

        train:
            dataloader:
                num_workers: 0
                batch_size: 1
                pin_memory: True

train: False
test: True
