# @package _global_

ablation_name: $ablation_name_nemo3d_align_feats_ext

ablation_name_nemo3d_align_feats_ext: dino_vits8_no_norm_acc

mesh_feats_type: 'M_dino_vits8_frozen_base_no_norm_T_centerzoom512_R_acc' # 'R_acc' # 'R_avg', 'R_avg_norm'

train_datasets:
  labeled:
    mesh_feats_type: ${mesh_feats_type}
  src:
    mesh_feats_type: ${mesh_feats_type}


