# @package _global_
ablation_name: multiview_mean_se3_bs8
method:
    nemo:
      multiview:
        type: multiview_mean_se3 # single multiview multiview_mean_se3
        batch_size: 8

train: False
test: True
