[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "OD3D"
authors = [
    {name = "Bla Bla", email = "blaa@bla.bla"},
]
description = "Neural Mesh, Render and Compare"
readme = "README.rst"
requires-python = ">=3.7"
keywords = ["3D", "detection", "object"]
license = {text = "BSD-3-Clause"}
dependencies = [
    "pytest",
    "pandas",
    "wget",
    "opencv-python",
    "torch",
    "torchvision",
    "torchaudio",
    "fvcore",
    "iopath",
    "pytorch3d@git+https://github.com/facebookresearch/pytorch3d@stable",
    "nvdiffrast@git+https://github.com/NVlabs/nvdiffrast",
    "git+https://github.com/limpbot/diff-gaussian-rasterization.git",
    "visdom",
    "tqdm",
    "requests",
    "h5py",
    "co3d@git+https://github.com/facebookresearch/co3d",
    "wandb",
    "cython",
    "pycocotools",
    "bboxtools",
    "scipy",
    "scikit-image",
    "gdown",
    "typer",
    "hydra-core",
    "plotly",
    "scikit-learn",
    "pygit2",
    "seaborn",
    "open3d",
    "numba",
    "pycuda",
    "timm",
    "tvb-gdist",
]

dynamic = ["version"]

#[project.optional-dependencies]

[project.scripts]
od3d = "od3d.cli._entry:main"
