name: nemo
class_name: NeMo
# class_name: nemo.models.nemo_cls.NeMoCls

num_noise: 5
max_group: 512
down_sample_rate: 8

classes: ${train_dataset.categories}

transforms:
    - class_name: nemo.datasets.pascal3d.Normalize

train:
  incremental:
    enabled: False
  transform:
    W: 512
    H: 512
    dist: 14.
  apply_txtr: False
  epochs_to_next_ckpt: 5
  epochs_to_next_val: 5
  epochs_to_next_forget_est_tforms4x4: 10
  epochs_to_next_test: 20
  epochs: 200
  batch_accumulate_to_next_step: 2
  T: 0.07
  optimizer:
    class_name: torch.optim.Adam
    lr: 0.0001 # 0.0001
    weight_decay: 0.0001

  scheduler:
    class_name: torch.optim.lr_scheduler.MultiStepLR
    milestones:
      - 400
      - 600
    gamma: 0.2

test:
    transform:
        W: 512
        H: 512
        dist: 14.

    dataloader:
        num_workers: 0
        batch_size: 1
        pin_memory: True

inference:
    sample:
      method: epnp3d2d # epnp3d2d uniform
      epnp3d2d:
        count_cams: 100
        count_pts: 4
    visualize:
        live: False
        samples: False
        verts_ncds_in_rgb: False
        net_feats_nearest_verts: False
        sim: False

    pose_iterative_refine: True

    optimizer:
        beta0: 0.4
        beta1: 0.6
        lr: 2e-2 # 5e-3 5e-2
        epochs: 30 # 30

    azim:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 10.
        steps: 10

    elev:
        min: -math.pi / 2
        max: math.pi / 2
        steps: 6

    theta:
        min: '0.'
        max: math.pi * 2 - (math.pi * 2) / 10.
        steps: 10

    #elev:
    #    min: -math.pi / 8
    #    max: math.pi / 4
    #    steps: 6

    #theta:
    #    min: -math.pi / 6
    #    max: math.pi / 6
    #    steps: 3

    dist:
        min: '20.'
        max: '20.'
        steps: 1


backbone:
    class_name: ResNetExt #  ResNetExt # ResNetExt DINOv2 ResNet
    net_type: resnetext
    local_size:
        - 1
        - 1
    noise_on_mask: false
    output_dimension: 128
    reduce_function: None
    pretrain: true
    # n_noise_points: 5 # duplicate of num_noise?

    width: 64
    height: 64
    channels: 128 # 128


memory_bank:
    class_name: nemo.models.feature_banks_cls.NearestMemoryManager
    input_size: 128
    K: 1
    momentum: 0.96
