defaults:
  - nemo

class_name: NeMo_Incremental

checkpoint: ${platform.path_exps}/08-07_14-10-07_CO3D_NeMo_train_co3d_3s_split_seq_separated_slurm/nemo.ckpt

train:
  val: True
  epochs: 100
  incremental:
    enabled: True
    sequences_labeled_count: 3
    sequences_new_pseudo_labeled_count: 3
    pseudo_label_multiview_count: 8
    pseudo_label_threshold: 0.6 # 0.6

  #sequences_tform4x4_labeled_count: 3 # how many sequences at start
  #sequences_tform4x4_estimated_frames_count: 4
  #sequences_tform4x4_est_sim_min: 0.6
  #sequences_tform4x4_est_transl_consist_max: 1. # = 1m
  #sequences_tform4x4_est_rot_consist_max: 0.5236 # pi / 6 = 30 degree
  #sequences_new_proposals_count: 10

