name: nemo
class_name: NeMo

num_noise: 5
max_group: 512
down_sample_rate: 8

classes: ${train_dataset.categories}

transforms:
    - class_name: nemo.datasets.pascal3d.Normalize

train:
  val: True
  transform:
    color_random: True
    W: 512
    H: 512
    dist: #  None #  None #15.
    dist_min:
    dist_max:
    center3d_min:
      - -0.5
      - -0.5
      - -0.5
    center3d_max:
      - +0.5
      - +0.5
      - +0.5
  apply_txtr: False
  epochs_to_next_ckpt: 5
  epochs_to_next_val: 5
  epochs_to_next_forget_est_tforms4x4: 10
  epochs_to_next_test: 20
  epochs: 200
  batch_accumulate_to_next_step: 2
  T: 0.07
  optimizer:
    class_name: torch.optim.Adam
    lr: 1e-4 # 0.0001
    weight_decay: 0.0001

  scheduler:
    class_name: torch.optim.lr_scheduler.MultiStepLR
    milestones:
      - 400
      - 600
    gamma: 0.2

  visualize:
      count_best: 3
      count_worst: 3
      count_rand: 1
      modalities:
        - 'gt_verts_ncds_in_rgb'
      samples_scores: True
      samples_sorted: True
      live: False

  val_fraction: 0.01

test:
    transform:
        W: 512
        H: 512
        dist: # 14.
        center3d: #

    dataloader:
        num_workers: 0
        batch_size: 1
        pin_memory: True

    visualize:
      count_best: 3
      count_worst: 3
      count_rand: 1
      modalities:
        - 'verts_ncds_in_rgb'
        - 'net_feats_nearest_verts'
        - 'sim_pxl'
        - 'samples'
      samples_scores: True
      samples_sorted: True
      live: False

inference:
    live: False
    sample:
      method: uniform # epnp3d2d uniform
      epnp3d2d:
        count_cams: 100
        count_pts: 4
      uniform:
        azim:
            min: '0.'
            max: math.pi * 2 - (math.pi * 2) / 12.
            steps: 12

        elev:
            min: -math.pi / 6
            max: math.pi / 3
            steps: 4

        theta:
            min: -math.pi / 6
            max: math.pi / 6
            steps: 3
    pose_iterative_refine: True
    optimizer:
        beta0: 0.4
        beta1: 0.6
        lr: 2e-2 # 5e-3 5e-2
        epochs: 30 # 30



backbone:
    class_name: ResNetExt #  ResNetExt # ResNetExt DINOv2 ResNet
    net_type: resnetext
    local_size:
        - 1
        - 1
    noise_on_mask: false
    output_dimension: 128
    reduce_function: None
    pretrain: true
    # n_noise_points: 5 # duplicate of num_noise?

    width: 64
    height: 64
    channels: 128 # 128

