defaults:
  - loss@train.selfsup.loss: crossentropy
  - optimizer@train.selfsup.optimizer: adam
  - scheduler@train.selfsup.scheduler: multistep
  - loss@train.sup.loss: crossentropy
  - optimizer@train.sup.optimizer: adam
  - scheduler@train.sup.scheduler: multistep
  - model@model: dinov2_frozen_base # _no_norm

name: selfsup
class_name: SelfSup

categories: ${train_datasets.labeled.categories}

model:
  backbone:
    freeze: True
    downsample_rate: 1 # 8, 14, 16,
    weights: 'default' # 'default' 'none'
    layers_returned: [ 1 ] # always start with deepest layer... 0 feat map, 1 cls feat,

    #stride: 8
    #hub_repo: 'facebookresearch/dino:main' # 'facebookresearch/dino:main', 'facebookresearch/dinov2'
    #hub_model: 'dino_vits8' # dino_vits8, dino_vitb8, dino_vits16, dino_vitb16, dinov2_vits14, dinov2_vitb14, dinov2_vitl14, dinov2_vitg14
  head:
    selfsup:
      class_name: ViT
      blocks:
        dim: 128
        depth: 0
        num_heads: 4 # not dim must be devisiable by num_heads
      fully_connected:
        out_dim: 10 # None means that there is no linear layer
      normalize: False
    sup:
      class_name: ViT
      blocks:
        dim: 128
        depth: 0
        num_heads: 4 # not dim must be devisiable by num_heads
      fully_connected:
        out_dim: 10 # None means that there is no linear layer
      normalize: False

train:
  selfsup:
    val: True
    split: random # 'random' 'sequences_separated' 'seqences_shared'

    transform:
      class_name: SequentialTransform
      transforms:
        - class_name: Identity
        - class_name: RGB_Random

    epochs_to_next_test: 1
    epochs: 5
    dataloader:
      num_workers: 4
      batch_size: 10
      pin_memory: True

    val_fraction: 0.01
    batch_accumulate_to_next_step: 2

    visualize:
      skip: True
      down_sample_rate: 4.
      count_best: 3
      count_worst: 3
      count_rand: 1
      modalities:
        - 'gt_verts_ncds_in_rgb'
      samples_scores: True
      samples_sorted: True
      live: False
  sup:
    val: True
    split: random # 'random' 'sequences_separated' 'seqences_shared'

    transform:
      class_name: SequentialTransform
      transforms:
        - class_name: Identity
        - class_name: RGB_Random

    epochs_to_next_test: 1
    epochs: 5
    dataloader:
      num_workers: 4
      batch_size: 10
      pin_memory: True

    val_fraction: 0.01
    batch_accumulate_to_next_step: 2

    visualize:
      skip: True
      down_sample_rate: 4.
      count_best: 3
      count_worst: 3
      count_rand: 1
      modalities:
        - 'gt_verts_ncds_in_rgb'
      samples_scores: True
      samples_sorted: True
      live: False


test:
  save_results: False
  transform:
      class_name: Identity

  dataloader:
      num_workers: 4
      batch_size: 100
      pin_memory: True

  visualize:
    down_sample_rate: 4.
    count_best: 3
    count_worst: 3
    count_rand: 1
    modalities:
      - 'pred_vs_gt_verts_ncds_in_rgb'
      - 'net_feats_nearest_verts'
      - 'sim_pxl'
      - 'samples'
    samples_scores: True
    samples_sorted: True
    live: False
