defaults:
  - optimizer@train.optimizer: adam
  - scheduler@train.scheduler: multistep
  - model@features: extractor_superpoint

name: transformer_matching
class_name: TransformerMatching


categories: ${train_datasets.labeled.categories}

lightglue:
  descriptor_dim: 256
  version: v0.1_arxiv
  url: 'https://github.com/cvg/LightGlue/releases/download/{}/{}_lightglue.pth'
  n_layers: 9
  num_heads: 4
  flash: True # enable FlashAttention if available.
  mp: False # enable mixed precision
  depth_confidence: 0.95 # early stopping, disable with -1
  width_confidence: 0.99 # point pruning, disable with -1
  filter_threshold: 0.1 # match threshold
  # Point pruning involves an overhead (gather).
  # Therefore, we only activate it if there are enough keypoints.
  pruning_keypoint_thresholds:
    cpu: -1
    mps: -1
    cuda: 1024
    flash: 1536
