# @package _global_

#train_datasets:
#  labeled:
#    path_cuboids: '${.path_preprocess}/mesh/cuboid1000'

#train_datasets:
#  labeled:
#    path_cuboids: '${.path_preprocess}/mesh/cuboid1000' # 250 500 1000
#
#method:
#    nemo:
#      checkpoint: ${platform.path_exps}/03-15_11-52-37_Pascal3D_NeMo_slurm/nemo.ckpt
#      # 03-15_11-52-37_Pascal3D_NeMo_slurm : cuboid1000
#      # 03-14_14-02-46_Pascal3D_NeMo_uniform_refine3d_mesh_slurm: cuboid250
##      # 12-08_10-37-47_Pascal3D_NeMo_epochs50_slurm
##      # 12-08_10-38-10_Pascal3D_NeMo_epochs100_slurm
##      # 12-08_10-37-58_Pascal3D_NeMo_epochs150_slurm
#
#      inference:
#        live: True
#train: False

#test:
#  dataloader:
#    batch_size: 2



