# @package _global_
defaults:
  - _thresh_p6_s3_f50_e10

ablation_name: incr_car_1s_3rd

method:
  nemo:
    checkpoint: ${platform.path_exps}/08-25_10-49-35_CO3D_NeMo_car_1s_3rd_slurm/nemo.ckpt

categories:
  - car

train_datasets:
  labeled:
    dict_nested_frames:
      car:
        '194_20939_43630':

val_datasets:
  main:
    dict_nested_frames:
      car:
        '185_19982_37678':
        '206_21799_45886':
        '194_20900_41097':
        '116_13655_29006':

test_datasets:
  co3d:
    dict_nested_frames:
      car:
        '206_21810_45890':
        '106_12650_23736':
        '206_21805_45881':
        '216_22836_48452':
        '216_22808_47498':
