# @package _global_
defaults:
  - override /datasets@train_datasets.labeled: co3d
  - override /datasets@train_datasets.unlabeled: co3d_40s_unlabeled
  - override /datasets@test_datasets.co3d: co3d
  - override /datasets@val_datasets.main: co3d

ablation_name: default

train_datasets:
  labeled:
    path_cuboids: ${.path_preprocess}/cuboids/avg/co3d_10s # ${.name}
    fpaths_cuboids:
      car: ${..path_cuboids}/car.ply # car/106_12650_23736.ply /cuboid_max_1000.ply
      bicycle: ${..path_cuboids}/bicycle.ply # car/106_12650_23736.ply /cuboid_max_1000.ply
      motorcycle: ${..path_cuboids}/motorcycle.ply # car/106_12650_23736.ply /cuboid_max_1000.ply
      airplane: ${..path_cuboids}/toyplane.ply # car/106_12650_23736.ply /cuboid_max_1000.ply

val_datasets:
  pascal3d:
    skip: False
  main:
    subset_fraction: 0.1

test_datasets:
  pascal3d:
    skip: False

method:
  nemo:
    train:
      optimizer:
        kwargs:
          lr: 1e-4 # 0.0001
          weight_decay: 0.0001

      early_stopping: False
      val: True
      split: sequences_separated # 'random' 'sequences_separated' 'seqences_shared'
      epochs_to_next_test: 1
      epochs: 10
      incremental:
        enabled: True
        sequences_labeled_count:
        frames_count_max_per_sequence: 50 # 6
        pseudo_labels_update:
          use_ground_truth: False
          epochs_to_next_update: 1
          count_new_labels_proposed: 20
          count_new_labels_selected_max: 3
          multiview_count: 6
          sim_threshold: 0.1 #0.1 # 0.6


#path_cuboids: ${.path_preprocess}/cuboids/avg/co3d_50s_train # ${.name}
#fpaths_cuboids:
#    car: ${..path_cuboids}/car.ply # car/106_12650_23736.ply /cuboid_max_1000.ply

train: True
test: True


