# @package _global_
ablation_name: incr
method:
    nemo:
      train:
        val: True
        epochs: 100
        incremental:
          enabled: True
          sequences_labeled_count: 3
          sequences_new_pseudo_labeled_count: 3
          pseudo_label_multiview_count: 4
          pseudo_label_threshold: 0.6


train: True
test: True
