# @package _global_
defaults:
  - /ablations/nemo_incremental@: _car_1s_1st

ablation_name: incr_car_1s_1st_newl20_sell5_f20

method:
  nemo:
    train:
      val: True
      split: sequences_separated # 'random' 'sequences_separated' 'seqences_shared'
      epochs_to_next_test: 4
      epochs: 100
      incremental:
        enabled: True
        sequences_labeled_count:
        frames_count_max_per_sequence: 20
        pseudo_labels_update:
          epochs_to_next_update: 1
          count_new_labels_proposed: 20
          count_new_labels_selected_max: 5
          multiview_count: 6
          sim_threshold: 0.1 # 0.6