# @package _global_
ablation_name: $ablation_name_nemo3d_align_feats_ext

ablation_name_nemo3d_align_feats_ext: dinov2_vitb14_no_norm_acc_dist_verts_min_min

mesh_feats_type: 'M_dinov2_vitb14_frozen_base_no_norm_T_centerzoom512_R_acc' # 'R_acc' # 'R_avg', 'R_avg_norm'

dist_verts_mesh_feats_reduce_type: 'min' # 'pca32_', 'avg', 'min', 'min_avg'

train_datasets:
  labeled:
    mesh_feats_type: ${mesh_feats_type}
    dist_verts_mesh_feats_reduce_type: ${dist_verts_mesh_feats_reduce_type}
  src:
    mesh_feats_type: ${mesh_feats_type}
    dist_verts_mesh_feats_reduce_type: ${dist_verts_mesh_feats_reduce_type}
