name: co3d
class_name: CO3D

path_co3d_raw: /misc/lmbraid19/sommerl/datasets/CO3D
path_co3d_preprocess: /misc/lmbraid19/sommerl/datasets/CO3D_Preprocess

rpath_dtd_raw: DTD
rpath_dtd_cache: DTD_cache
path_dtd_raw: ${platform.path_datasets}/${.rpath_dtd_raw}
path_dtd_cache: ${platform.path_datasets}/${.rpath_dtd_cache}

preprocess_meta_override: False
preprocess_meta_remove_previous: False
preprocess_pcls: False

sequences:
  - '106_12650_23736'
  #- '116_13655_29006'
  - '185_19982_37678'
  #- '194_20898_41093'
  #- '194_20900_41097'
  #- '194_20939_43630'
  #- '206_21799_45886'
  #- '206_21805_45881'
  #- '206_21810_45890'
  #- '216_22790_47232'
  #- '216_22808_47498'
  #- '216_22836_48452'

classes:
  - car
#  - apple
#  - backpack
#  - ball
#  - banana
#  - baseballbat
#  - baseballglove
#  - bench
#  - bicycle
#  - book
#  - bottle
#  - bowl
#  - broccoli
#  - cake
#  - car
#  - carrot
#  - cellphone
#  - chair
#  - couch
#  - cup
#  - donut
#  - frisbee
#  - hairdryer
#  - handbag
#  - hotdog
#  - hydrant
#  - keyboard
#  - kite
#  - laptop
#  - microwave
#  - motorcycle
#  - mouse
#  - orange
#  - parkingmeter
#  - pizza
#  - plant
#  - remote
#  - sandwich
#  - skateboard
#  - stopsign
#  - suitcase
#  - teddybear
#  - toaster
#  - toilet
#  - toybus
#  - toyplane
#  - toytrain
#  - toytruck
#  - tv
#  - umbrella
#  - vase
#  - wineglass
