defaults:
  - co3dv1_10s_zsp_labeled

name: co3dv1_10s_zsp_labeled_cuboid_ref

cuboid_source: 'zsp_ref_cuboid' #  'default', 'aligned', 'zsp_ref_cuboid', 'labeled'
cam_tform_obj_source: 'zsp_labeled_cuboid_ref' # 'droid_slam_zsp_labeled' 'droid_slam_labeled' 'droid_slam_aligned' 'droid_slam'

frames_count_max_per_sequence: 1
