defaults:
  - co3d_5s_no_zsp_labeled

name: co3d_5s_no_zsp_aligned

#frames_count_max_per_sequence: 3
#
#modalities:
#    - 'size'
#    - 'category'
#    - 'cam_intr4x4'
#    - 'cam_tform4x4_obj'
#    - 'category'
#    - 'rgb'
#    - 'mask'
#    - 'sequence_name'
#    - 'sequence'
#    - 'mesh'
#
#
#categories:
#  - 'car'

sequences_require_gt_pose: True

cuboid_source: 'aligned' #  'default', 'aligned', 'zsp_ref_cuboid', 'labeled'
cam_tform_obj_source: 'droid_slam_aligned' # 'droid_slam_labeled' 'droid_slam_aligned' 'droid_slam'
aligned_name: '5_to_5' # 'all_to_one_17_10_23_convex500_dinov2_acc_min'
