defaults:
  - co3dv1_10s_zsp_unlabeled

name: co3dv1_10s_zsp_labeled

#frames_count_max_per_sequence: 3
###
modalities:
    - 'size'
    - 'category'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    - 'category'
    - 'rgb'
    - 'mask'
    - 'sequence_name'
    - 'sequence'
    - 'depth'
    - 'depth_mask'
    # - 'mesh'

sequences_require_gt_pose: True

cuboid_source: 'default' #  'default', 'aligned', 'zsp_ref_cuboid', 'labeled'
cam_tform_obj_source: 'droid_slam_zsp_labeled' # 'droid_slam_zsp_labeled' 'droid_slam_labeled' 'droid_slam_aligned' 'droid_slam'

# categories:
#  - bicycle
#  - toytruck
#  - toytrain
#  - teddybear
#  - car
#  - toybus
#  - motorcycle
#  - keyboard
#  - handbag
#  - remote
#  - toyplane
#  - toilet
#  - hairdryer
#  - mouse
#  - toaster
#  - hydrant
#  - chair
#  - laptop
#  - book
#  - backpack