defaults:
  - co3d

name: co3d_only_first_1

frames_count_max_per_sequence: 1

sequences_require_pcl: True
sequences_require_pcl_score: -10. # 0.5
sequences_sort_pcl_score: True
sequences_count_max_per_category: 100

categories:
  - car