name: co3d
class_name: CO3D

modalities:
    - 'rgb'
    - 'mask'
    - 'cuboid_front_tform4x4_obj' # setting this is highly important, so that the cam_tform4x4_obj equals cam_tform4x4_cuboid_front
    - 'sequence_name'


return_cam_tform4x4_cuboid_front: True

path_co3d_raw: ${platform.path_datasets}/CO3D
path_co3d_preprocess: ${platform.path_datasets}/CO3D_Preprocess

path_meta: ${.path_co3d_preprocess}/meta

rpath_dtd_raw: DTD
rpath_dtd_cache: DTD_cache
path_dtd_raw: ${platform.path_datasets}/${.rpath_dtd_raw}
path_dtd_cache: ${platform.path_datasets}/${.rpath_dtd_cache}

setup: True
setup_remove_previous: False
setup_override: False

preprocess: True
preprocess_meta_override: False
preprocess_meta_remove_previous: False
preprocess_cuboids_override: False
preprocess_front_names_override: False

sequences:
  - '106_12650_23736'
  - '116_13655_29006'
  - '185_19982_37678'
  - '194_20898_41093'
  - '194_20900_41097'
  - '194_20939_43630'
  #- '206_21799_45886'
  #- '206_21805_45881'
  #- '206_21810_45890'
  #- '216_22790_47232'
  #- '216_22808_47498'
  #- '216_22836_48452'


path_cuboids: ${.path_co3d_preprocess}/cuboids
fpaths_cuboids:
    car: ${..path_cuboids}/car/106_12650_23736.ply # /cuboid_max_1000.ply

classes:
  - car
#  - apple
#  - backpack
#  - ball
#  - banana
#  - baseballbat
#  - baseballglove
#  - bench
#  - bicycle
#  - book
#  - bottle
#  - bowl
#  - broccoli
#  - cake
#  - car
#  - carrot
#  - cellphone
#  - chair
#  - couch
#  - cup
#  - donut
#  - frisbee
#  - hairdryer
#  - handbag
#  - hotdog
#  - hydrant
#  - keyboard
#  - kite
#  - laptop
#  - microwave
#  - motorcycle
#  - mouse
#  - orange
#  - parkingmeter
#  - pizza
#  - plant
#  - remote
#  - sandwich
#  - skateboard
#  - stopsign
#  - suitcase
#  - teddybear
#  - toaster
#  - toilet
#  - toybus
#  - toyplane
#  - toytrain
#  - toytruck
#  - tv
#  - umbrella
#  - vase
#  - wineglass
