defaults:
  - co3dv1_10s_zsp_labeled

name: co3dv1_10s_zsp_labeled_cuboid_ref

pcl_source: 'co3d_clean'
cuboid_source: 'zsp_ref_cuboid' #  'default', 'aligned', 'zsp_ref_cuboid', 'labeled'
cam_tform_obj_source: 'zsp_labeled_cuboid_ref' # 'droid_slam_zsp_labeled' 'droid_slam_labeled' 'droid_slam_aligned' 'droid_slam'

#modalities:
#    - 'size'
#    - 'category'
#    - 'cam_intr4x4'
#    - 'cam_tform4x4_obj'
#    - 'category'
#    - 'rgb'
#    - 'mask'
#    - 'sequence_name'
#    - 'sequence'
#    - 'mesh'
#frames_count_max_per_sequence: 3
#
#categories:
##  - bicycle
##  - toytruck
##  - toytrain
##  - teddybear
##  - car
##  - toybus
##  - motorcycle
##  - keyboard
##  - handbag # ?
#  - remote # relabel
##  - toyplane
##  - toilet
##  - hairdryer # ?
##  - mouse
##  - toaster
##  - hydrant
##  - chair
##  - laptop
##  - book # ?
##  - backpack