name: coco
class_name: COCO

modalities:
    - 'rgb'
    - 'categories'
    # - 'mask'

path_raw: ${platform.path_datasets}/COCO
path_preprocess: ${platform.path_datasets}/COCO_Preprocess

setup_remove_previous: False
setup_override: False

preprocess_meta_remove_previous: False
preprocess_meta_override: False