name: dtd
class_name: DTD

modalities:
    - 'rgb'
    - 'size'

path_raw: ${platform.path_datasets}/DTD
path_preprocess: ${platform.path_datasets}/DTD_Preprocess

setup_remove_previous: False
setup_override: False

preprocess_meta_remove_previous: False
preprocess_meta_override: False

dict_nested_frames:
  val:
  train: