name: imagenet
class_name: ImageNet

modalities:
  - 'rgb'
  #- 'category'
  - 'size'
  - 'bbox'

path_raw: ${platform.path_datasets}/ImageNet
path_preprocess: ${platform.path_datasets}/ImageNet_Preprocess

setup_remove_previous: False
setup_override: False

preprocess_meta_remove_previous: False
preprocess_meta_override: False

credentials:
  kaggle: ${credentials.kaggle}

#dict_nested_frames: # 'train_cls', 'train_loc', 'val', 'test']
#    test:
#        car:

#categories:
#    - 'car'

