name: monolmb
class_name: MonoLMB

modalities:
    - 'size'
    - 'category'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    - 'rays_center3d'
    - 'category'
    - 'rgb'
    #- 'mask'
    #- 'sequence_name'
    #- 'sequence'
    # - 'mesh'

mesh_name: 'alpha500' # 'convex500', 'voxel500' 'poisson500', 'alpha500'
pcl_source: 'droid_slam_clean'

cuboid_source: 'droid_slam' #'kpts2d_orient_and_pcl', 'front_frame_and_pcl', 'limits3d', 'droid_slam'
cam_tform_obj_source: 'droid_slam'  # 'kpts2d_orient_and_pcl' #'kpts2d_orient_and_pcl', 'front_frame_and_pcl', 'first_frame', 'front_frame', 'limits3d', 'droid_slam'

mesh_feats_type: 'M_dinov2_frozen_base_T_centerzoom512_R_acc' # 'R_acc' # 'R_avg', 'R_avg_norm'
dist_verts_mesh_feats_reduce_type: 'min' # 'avg', 'min'

frames_count_max_per_sequence:
block_negative_depth: False

path_raw: ${platform.path_datasets}/MonoLMB
path_preprocess: ${platform.path_datasets}/MonoLMB_Preprocess

setup:
  enabled: False
  override: False
  remove_previous: False

extract_meta:
  enabled: False
  override: False
  remove_previous: False

preprocess:
  sfm:
    enabled: False
    override: False
  mask:
    enabled: True
    override: False


#dict_nested_frames:
#  car:
#    '185_19982_37678':
#    '206_21799_45886':
#    '194_20939_43630':
#    '194_20900_41097':
#    '116_13655_29006':
#    '206_21810_45890':
#    '106_12650_23736':
#    '206_21805_45881':
#    '216_22836_48452':
#    '216_22808_47498':