name: pascal3d
class_name: Pascal3D

modalities:
    - 'rgb'
    - 'mask'
    - 'kpts'
    - 'bbox'


url_pascal3d_raw: ftp://cs.stanford.edu/cs/cvgl/PASCAL3D+_release1.1.zip
rpath_pascal3d_raw: PASCAL3D+_release1.1

path_raw: ${platform.path_datasets}/${.rpath_pascal3d_raw}
path_preprocess: ${platform.path_datasets}/PASCAL3D_Preprocess

rpath_dtd_raw: DTD
rpath_dtd_cache: DTD_cache
path_dtd_raw: ${platform.path_datasets}/${.rpath_dtd_raw}
path_dtd_cache: ${platform.path_datasets}/${.rpath_dtd_cache}

rpath_meshes: ${.rpath_pascal3d_raw}/CAD
path_meshes: ${platform.path_datasets}/${.rpath_meshes}


path_cuboids: '${.path_preprocess}/cuboids'
fpaths_cuboids:
    aeroplane: ${..path_cuboids}/aeroplane.ply
    bicycle: ${..path_cuboids}/bicycle.ply
    boat: ${..path_cuboids}/boat.ply
    bottle: ${..path_cuboids}/bottle.ply
    bus: ${..path_cuboids}/bus.ply
    car: ${..path_cuboids}/car.ply
    chair: ${..path_cuboids}/chair.ply
    diningtable: ${..path_cuboids}/diningtable.ply
    motorbike: ${..path_cuboids}/motorbike.ply
    sofa: ${..path_cuboids}/sofa.ply
    train: ${..path_cuboids}/train.ply
    tvmonitor: ${..path_cuboids}/tvmonitor.ply

scale_normalized_to_real:
    aeroplane: 1.
    bicycle: 1.
    boat: 1.
    bottle: 1.
    bus: 1.
    car: 4.65
    chair: 1.
    diningtable: 1.
    motorbike: 1.
    sofa: 1.
    train: 1.
    tvmonitor: 1.

path_shapenemo: ${platform.path_datasets}/ShapeNeMo/Pascal3D

url_pascal3d_seg: https://docs.google.com/uc?export=download&id=1hx6eErHtuR7TCGlQMyl2_03gXDTQw3Qm
rpath_pascal3d_seg: PASCAL3D_Seg
path_pascal3d_seg: ${platform.path_datasets}/${.rpath_pascal3d_seg}

setup: True
setup_remove_previous: False
setup_override: False
preprocess: True
preprocess_meta_override: False
preprocess_meta_remove_previous: False
preprocess_cuboids_override: False

index_shift: 0
pad_texture: false
remove_no_bg: 8
center: true
resize: true
resize_dists_min: 5.
resize_dists_max: 10.

cache: # None, Disk, RAM

# enable_cache: true
# weighted: true
#training_only: false
#evaluation_only: false
#augment_by_dist: false
#prepare_mode: first
#center_and_resize: true
#skip_3d_anno: false

occ_level: 0
occ_levels:
    train: [0]
    val: [0, 1, 2, 3]


image_sizes:
    aeroplane: [512, 512]
    bicycle: [512, 512]
    boat: [512, 512]
    bottle: [512, 512]
    bus: [512, 512]
    car: [512, 512]
    chair: [512, 512]
    diningtable: [512, 512]
    motorbike: [512, 512]
    sofa: [512, 512]
    train: [512, 512]
    tvmonitor: [512, 512]

#image_sizes:
#    aeroplane: [320, 672]
#    bicycle: [608, 608]
#    boat: [384, 672]
#    bottle: [480, 800]
#    bus: [320, 736]
#    car: [256, 672]
#    chair: [608, 384]
#    diningtable: [384, 800]
#    motorbike: [512, 512]
#    sofa: [352, 736]
#    train: [256, 608]
#    tvmonitor: [480, 448]

classes:
#    - aeroplane
#    - bicycle
#    - boat
#    - bottle
#    - bus
    - car
#    - chair
#    - diningtable
#    - motorbike
#    - sofa
#    - train
#    - tvmonitor

#transforms:
#    - class_name: od3d.datasets.transforms.ToTensor
#sampler: None

# root_path: data/PASCAL3D_NeMo
#seg_data_url: https://docs.google.com/uc?export=download&id=1hx6eErHtuR7TCGlQMyl2_03gXDTQw3Qm
#seg_data_path: data/PASCAL3D_segmentation
