defaults:
  - logger: wandb
  - methods@method.nemo: nemo
  - methods/dataset@method.nemo: co3d
  - datasets@train_datasets.labeled: co3d_10s_zsp_aligned # co3d_5s_train #  co3d_50s_train # co3d_50s_train, co3d_train, pascal3d_train
  - datasets@val_datasets.main: co3d_10s_zsp_labeled #  pascal3d_val # pascal3d_val
  #- datasets@val_datasets.pascal3d: # pascal3d_val
  - datasets@val_datasets.pascal3d: pascal3d_val # co3d_5s_zero_shot_pose_aligned # pascal3d_val co3d_5s_test # co3d_10s_test, co3d_test
  - datasets@test_datasets.co3d: co3d_10s_zsp_labeled
  - datasets@test_datasets.pascal3d: pascal3d_test
  - datasets@texture_dataset: dtd
  - platform@platform_local: local
  - platform: local

categories:
  - bicycle
  - truck
  - train
  - teddybear
  - car
  - bus
  - motorcycle
  - keyboard
  - handbag
  - remote
  - airplane
  - toilet
  - hairdryer
  - mouse
  - toaster
  - hydrant
  - chair
  - laptop
  - book
  - backpack

#  (sofa, tv, bottle)
#pascal3d_categories:
#  - bicycle
#  - train
#  - car
#  - bus
#  - motorcycle
#  - airplane
#  - chair

metrics:
  - metricA
  - metricB

aligned_name: 'all_to_one_17_10_23_convex500_dinov2_acc_min' # 'all_to_one_13_10_23' 'all_to_one_12_10_23'
method:
  nemo:
    inference:
      pre_rendered: False
    train:
      epochs: 20
      dataloader:
        num_workers: 4
        batch_size: 12
    categories: ${categories}
    #fpaths_meshes: ${train_datasets.labeled.fpaths_cuboids}
    path_meshes: ${train_datasets.labeled.path_preprocess}/aligned/${aligned_name}/mesh
    fpaths_meshes:
      bicycle: ${..path_meshes}/bicycle/mesh.ply # car/106_12650_23736.ply /cuboid_max_1000.ply
      truck: ${..path_meshes}/toytruck/mesh.ply
      train: ${..path_meshes}/toytrain/mesh.ply
      teddybear: ${..path_meshes}/teddybear/mesh.ply
      car: ${..path_meshes}/car/mesh.ply
      bus: ${..path_meshes}/toybus/mesh.ply
      motorcycle: ${..path_meshes}/motorcycle/mesh.ply
      keyboard: ${..path_meshes}/keyboard/mesh.ply
      handbag: ${..path_meshes}/handbag/mesh.ply
      remote: ${..path_meshes}/remote/mesh.ply
      airplane: ${..path_meshes}/toyplane/mesh.ply
      toilet: ${..path_meshes}/toilet/mesh.ply
      hairdryer: ${..path_meshes}/hairdryer/mesh.ply
      mouse: ${..path_meshes}/mouse/mesh.ply
      toaster: ${..path_meshes}/toaster/mesh.ply
      hydrant: ${..path_meshes}/hydrant/mesh.ply
      chair: ${..path_meshes}/chair/mesh.ply
      laptop: ${..path_meshes}/laptop/mesh.ply
      book: ${..path_meshes}/book/mesh.ply
      backpack: ${..path_meshes}/backpack/mesh.ply


train_datasets:
  labeled:
    aligned_name: ${aligned_name}
    categories: ${categories}

val_datasets:
  main:
    categories: ${categories}
  pascal3d:
    categories: ${categories}

test_datasets:
  co3d:
    categories: ${categories}
  pascal3d:
    categories: ${categories}

train: True
test: True
