defaults:
  - logger: wandb
  - methods@method.nemo: nemo
  - methods/nemo_incremental@method.nemo: co3d
  - datasets@train_dataset: co3d_55s_train #  co3d_50s_train # co3d_50s_train, co3d_train, pascal3d_train
  - datasets@val_datasets.pascal3d: pascal3d_val
  - datasets@test_datasets.co3d: co3d_5s_test # co3d_10s_test, co3d_test
  - datasets@test_datasets.pascal3d: pascal3d_test
  - platform@platform_local: local
  - platform: local

metrics:
  - metricA
  - metricB

train: True
test: True
