defaults:
  - logger: wandb
  - methods@method.nemo: nemo
  - methods/dataset@method.nemo: pascal3d
  - datasets@train_datasets.labeled: pascal3d_train #  co3d_50s_train # co3d_50s_train, co3d_train, pascal3d_train
  - datasets@val_datasets.main: pascal3d_val
  - datasets@test_datasets.pascal3d: pascal3d_test
  - datasets@texture_dataset: dtd
  - platform@platform_local: local
  - platform: local
  - datasets/categories@categories: pascal3d

metrics:
  - metricA
  - metricB

method:
  nemo:
    checkpoint: ${platform.path_exps}/08-28_09-14-15_Pascal3D_NeMo_slurm/nemo.ckpt # 08-28_09-14-15_Pascal3D_NeMo_slurm, 08-25_17-08-51_Pascal3D_NeMo_slurm

train: True
test: True

train_datasets:
  labeled:
    #subset_fraction: 0.1
    categories: ${categories}

val_datasets:
  main:
    #subset_fraction: 0.001
    categories: ${categories}

test_datasets:
  pascal3d:
    #subset_fraction: 0.01
    categories: ${categories}
    #dict_nested_frames:
    #   val:
    #      bus:
    #        - "n04146614_2398"
