# @package _global_
defaults:
  - /ablations/nemo/inference/_default

ablation_name_nemo_distribution: 'vMF_normalize_img'

method:
  nemo:
    #checkpoint: ${platform.path_exps}/01-25_23-03-17_Pascal3D_NeMo_von_mises_fisher_normalize_img_slurm/nemo.ckpt
    bank_feats_normalize: False
    bank_feats_distribution: 'von-mises-fisher' # 'von-mises-fisher', 'gaussian'
    train:
      T: 1.
    model:
        normalize: True