# checkpoint: ${platform.path_exps}/NeMo-Classification/2022_09_26/classification_saved_model_199.pth
# checkpoint_old: ${platform.path_exps}/NeMo-Classification/classification_saved_model_199.pth

train:
    # val: False
    epochs: 200 # artur: 200  wufei: 800
    dataloader:
        num_workers: 4
        batch_size: 12 # artur: 24/32 wufei: 108
        pin_memory: True

test:
    dataloader:
        num_workers: 4
        batch_size: 4
        pin_memory: True