# @package _global_
defaults:
  - override /datasets@train_datasets.labeled: co3d_5s_no_zsp_labeled # co3d_5s_no_zsp_labeled co3d_50s_no_zsp co3dv1_50s_no_zsp co3dv1_10s_zsp_unlabeled co3d_3s_no_zsp
  - override /datasets@train_datasets.src: co3d_5s_no_zsp_labeled # co3d_5s_no_zsp_labeled co3d_50s_no_zsp co3dv1_50s_no_zsp co3dv1_10s_zsp_unlabeled co3d_3s_no_zsp
  - override /datasets@val_datasets.main:
  - override /datasets@test_datasets.co3d: co3d_5s_no_zsp_labeled # co3d_5s_no_zsp_labeled co3d_50s_no_zsp co3dv1_10s_zsp_labeled co3d_10s_test, co3d_test

ablation_name: src_5s_ref_5s

categories:
  - bicycle
  - truck
  - train
  - teddybear
  - car
  - bus
  - motorcycle
  - keyboard
  - handbag
  - remote
  - airplane
  - toilet
  - hairdryer
  - mouse
  - toaster
  - hydrant
  - chair
  - laptop
  - book
  - backpack
  - cellphone # from cellphone on, no zsp categories
  - bench
  - bottle
  - couch
  - cup
  - suitcase
  - tv

method:
  nemo:
    use_gt_src: True
    use_only_first_reference: False
    dist_appear_weight: 0.5
    use_appear_argmin: False
    global_optimization_steps: 1
    categories: ${categories}
    aligned_name: 'latest'
    aligned_store_only_similar: True

