# @package _global_

ablation_name: nll_affine_to_prob_bank_loss_gradient

method:
  nemo:
    train:
      loss: nll_affine_to_prob # cross_entropy, nll_softmax, nll_clip, nll_affine_to_prob, l2, l2_squared
      bank_feats_update: loss_gradient # loss_gradient, normalize_loss_gradient, moving_average
      T: 0.07
      alpha: 0.96