# @package _global_
#defaults:
#  - override /datasets@val_datasets.pascal3d:
#  - override /datasets@test_datasets.pascal3d:

ablation_name: laptop

aligned_name: 'all_to_one_c3_s50' # 'all_to_one_13_10_23' 'all_to_one_12_10_23'

categories:
  - laptop


val_datasets:
  pascal3d:
    skip: True

test_datasets:
  pascal3d:
    skip: True