# @package _global_
ablation_name: lr1e-4_bs24
method:
    nemo:
        train:
          optimizer:
              lr: 1e-4 # 0.0001
          batch_accumulate_to_next_step: 2
          dataloader:
              batch_size: 12
