# @package _global_

ablation_name: moving_average

#train_datasets:
#    labeled:
#      subset_fraction: 0.01

method:
  nemo:
    train:
      # val: False
      loss: cross_entropy # cross_entropy, nll_softmax, nll_clip, nll_affine_to_prob, l2, l2_squared
      bank_feats_update: moving_average # loss_gradient, normalize_loss_gradient, moving_average
      T: 0.07
      alpha: 0.96