# @package _global_

train_dataset:
  subset: 0.01

ablation_name: regression_resnet

method:
  regression:
    model:
      backbone:
        class_name: ResNet
        #layers_returned: [ 4, ] # always start with depest layer...
      head:
        class_name: ResNet
        conv_blocks:
          out_dims: [2048]
          strides: [1]
        fully_connected:
          out_dim: 3 # None means that there is no linear layer

