backbone:
  class_name: DINOv2
  weights: 'default' # 'default' 'none'
  freeze: True
  layers_returned: [ 0 ] # always start with deepest layer...
head:
  class_name: ResNet
  block_type: 'bottleneck' # 'bottleneck', 'basic'
  conv_blocks:
    out_dims: [] #  [ 512, 512, 128 ]
    strides: [] #  [ 1, 1, 1 ]
    pre_upsampling: [] # [1., 1., 2.]
  fully_connected:
    out_dim: # None means that there is no linear layer
  normalize: True
