# @package _global_
ablation_name: incr_l3
method:
    nemo:
      train:
        test: False
        incremental:
          enabled: True
        sequences_tform4x4_labeled_count: 3 # how many sequences at start
        sequences_tform4x4_estimated_frames_count: 8
        sequences_tform4x4_est_sim_min: 0.6
        sequences_tform4x4_est_transl_consist_max: 1. # = 1m
        sequences_tform4x4_est_rot_consist_max: 0.5236 # pi / 6 = 30 degree
        sequences_new_proposals_count: 10

        optimizer:
            class_name: torch.optim.Adam
            lr: 1e-4 # 0.0001
            weight_decay: 0.0001

        batch_accumulate_to_next_step: 2

        epochs_to_next_ckpt: 1 # 6
        epochs_to_next_val: 1 # 6
        epochs_to_next_test: 1 # 6
        epochs_to_next_forget_est_tforms4x4: 2
        epochs: 100


train: True
test: False
