# @package _global_
ablation_name: incr_l3
method:
    nemo:
      train:

        incremental:
          enabled: True
        sequences_tform4x4_labeled_count: 3 # how many sequences at start
        sequences_tform4x4_estimated_frames_count: 8
        sequences_tform4x4_estimated_sim_threshold: 0.6
        optimizer:
            class_name: torch.optim.Adam
            lr: 1e-4 # 0.0001
            weight_decay: 0.0001

        batch_accumulate_to_next_step: 2

        epochs_to_next_ckpt: 1 # 6
        epochs_to_next_val: 1 # 6
        epochs_to_next_test: 1 # 6
        epochs_to_next_forget_est_tforms4x4: 2
        epochs: 100
