# @package _global_
ablation_name: incr_th06
method:
    nemo:
      train:
        val: True
        epochs: 100
        incremental:
          enabled: True
          pseudo_label_threshold: 0.6


train: True
test: True
