# @package _global_
defaults:
  - /ablations/categories/cross/_default
  #- /ablations/categories/cross/_add_pascal3d
  - /ablations/categories/cross/_add_objectnet3d
  - /ablations/categories/cross/_add_co3dv1_10s_zsp_labeled
  - override /methods@method.nemo: nemo_incremental

ablation_name: incr_cat1_keyboard

#self:
#  config:
#    train:
#      incremental:
#        decay_labeled:
method:
  nemo:
    train:
      val: False
      split: sequences_separated # 'random' 'sequences_separated' 'seqences_shared'
      epochs_to_next_test: 1
      epochs: 10
      incremental:
        epoch_frames_count: 5000
        decay_labeled: 0.5
        enabled: True
        sequences_labeled_count:
        frames_count_max_per_sequence: # 20
        pseudo_labels_update:
          use_ground_truth: False
          epochs_to_next_update: 1
          count_new_labels_proposed: 10
          count_new_labels_selected_max: 10
          multiview_count: 4
          sim_threshold: -1. # 0.1 # 0.6

categories:
#  - bicycle
#  - truck
#  - train
#  - teddybear
#  - car
#  - bus
#  - motorcycle
  - keyboard
#  - handbag
#  - remote
#  - airplane
#  - toilet
#  - hairdryer
#  - mouse
#  - toaster
#  - hydrant
#  - chair
#  - laptop
#  - book
#  - backpack
#  - cellphone # from cellphone on, no zsp categories
#  - bench
#  - bottle
#  - couch
#  - cup
#  - suitcase
#  - tv